Watching for file changes with StatReloader
/home/yousef/Documents/Django Workspace/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/yousef/Documents/Django Workspace/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/yousef/Documents/Django Workspace/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/yousef/Documents/Django Workspace/storefront/storefront/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Calling httpbin
Recieved the response
/home/yousef/Documents/Django Workspace/storefront/storefront/settings.py changed, reloading.
2022-05-21 22:14:51,502 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-05-21 22:14:54,868 (INFO) - playground.views - Calling httpbin
2022-05-21 22:14:57,127 (INFO) - playground.views - Recieved the response
2022-05-21 22:25:10,642 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/manage.py changed, reloading.
2022-05-21 22:26:11,145 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-05-22 19:01:05,724 (WARNING) - django.request - Unauthorized: /store/collections/
2022-05-22 19:01:05,760 (WARNING) - django.request - Forbidden: /store/collections/
2022-05-22 19:01:05,783 (WARNING) - django.request - Bad Request: /store/collections/
2022-05-22 19:01:05,969 (WARNING) - django.request - Not Found: /store/collections/-1/
2022-05-22 19:01:05,997 (WARNING) - django.request - Unauthorized: /store/products/
2022-05-22 19:01:06,032 (WARNING) - django.request - Forbidden: /store/products/
2022-05-22 19:01:06,065 (WARNING) - django.request - Bad Request: /store/products/
2022-05-22 19:02:58,405 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/storefront/settings/common.py changed, reloading.
2022-05-22 19:03:00,238 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-05-22 19:03:08,164 (WARNING) - django.request - Unauthorized: /store/collections/
2022-05-22 19:03:08,214 (WARNING) - django.request - Forbidden: /store/collections/
2022-05-22 19:03:08,272 (WARNING) - django.request - Bad Request: /store/collections/
2022-05-22 19:03:08,497 (WARNING) - django.request - Not Found: /store/collections/-1/
2022-05-22 19:03:08,571 (WARNING) - django.request - Unauthorized: /store/products/
2022-05-22 19:03:08,637 (WARNING) - django.request - Forbidden: /store/products/
2022-05-22 19:03:08,718 (WARNING) - django.request - Bad Request: /store/products/
2022-05-22 19:03:21,355 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-05-22 19:03:31,043 (WARNING) - django.request - Unauthorized: /store/collections/
2022-05-22 19:03:31,094 (WARNING) - django.request - Forbidden: /store/collections/
2022-05-22 19:03:31,145 (WARNING) - django.request - Bad Request: /store/collections/
2022-05-22 19:03:31,326 (WARNING) - django.request - Not Found: /store/collections/-1/
2022-05-22 19:03:31,396 (WARNING) - django.request - Unauthorized: /store/products/
2022-05-22 19:03:31,456 (WARNING) - django.request - Forbidden: /store/products/
2022-05-22 19:03:31,508 (WARNING) - django.request - Bad Request: /store/products/
2022-05-22 19:07:31,127 (WARNING) - django.request - Method Not Allowed: /store/carts/
2022-08-22 18:53:21,418 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-22 18:53:27,502 (WARNING) - django.request - Not Found: /favicon.ico
2022-08-22 18:53:43,127 (WARNING) - silk.model_factory - Response to request with pk 4f149107-1108-408b-8cf1-05a23b05c52f has content type text/javascript but was unable to parse it
2022-08-22 18:53:52,578 (WARNING) - silk.model_factory - Response to request with pk 8557d8b5-aad0-45a3-bb99-c6818d6b6c24 has content type text/javascript but was unable to parse it
2022-08-22 18:54:00,116 (WARNING) - silk.model_factory - Response to request with pk f8c8d4fe-535c-4104-b093-644459ef0b3a has content type text/javascript but was unable to parse it
2022-08-22 18:54:11,471 (WARNING) - silk.model_factory - Response to request with pk 292b7825-c702-4305-bd60-83a368023760 has content type text/javascript but was unable to parse it
2022-08-22 18:54:39,286 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-22 18:54:43,217 (WARNING) - django.request - Unauthorized: /store/orders/
2022-08-22 18:54:46,880 (WARNING) - django.request - Unauthorized: /store/orders/24/
2022-08-22 19:24:05,921 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-22 19:24:23,094 (WARNING) - django.request - Not Found: /store/media
2022-08-22 19:24:35,212 (WARNING) - silk.model_factory - Response to request with pk 99be48aa-f90e-469c-be3f-d5a5c44afcc2 has content type text/javascript but was unable to parse it
2022-08-22 19:24:40,050 (WARNING) - silk.model_factory - Response to request with pk 5174052a-27c9-43d6-ac79-6c1880e8e842 has content type text/javascript but was unable to parse it
2022-08-22 19:24:43,064 (WARNING) - silk.model_factory - Response to request with pk 815f662e-6e13-4e8a-b222-87e5e0952ffa has content type text/javascript but was unable to parse it
2022-08-22 19:24:59,782 (WARNING) - django.request - Not Found: /media/store/images
2022-08-22 19:25:02,342 (WARNING) - django.request - Not Found: /media/store/images/
2022-08-22 19:25:21,185 (WARNING) - silk.model_factory - Response to request with pk a6246d74-c3cb-4397-9642-170b58c32875 has content type text/javascript but was unable to parse it
2022-08-22 19:25:21,464 (WARNING) - django.request - Not Found: /media/headphones-red.webp
2022-08-22 19:25:33,661 (WARNING) - silk.model_factory - Response to request with pk 1cca5773-811c-48c5-9714-c72e78a7d8a7 has content type text/javascript but was unable to parse it
2022-08-22 19:25:38,297 (WARNING) - silk.model_factory - Response to request with pk 5642cf3e-87e7-4ca3-b320-de40615ff96e has content type text/javascript but was unable to parse it
2022-08-22 19:25:54,610 (ERROR) - django.request - Internal Server Error: /admin/store/product/648/change/
Traceback (most recent call last):
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1888, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1745, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1798, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1248, in save_related
    self.save_formset(request, form, formset, change=change)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1236, in save_formset
    formset.save()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/forms/models.py", line 786, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/forms/models.py", line 945, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/forms/models.py", line 1141, in save_new
    return super().save_new(form, commit=commit)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/forms/models.py", line 762, in save_new
    return form.save(commit=commit)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/forms/models.py", line 548, in save
    self.instance.save()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1620, in execute_sql
    for sql, params in self.as_sql():
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1547, in as_sql
    value_rows = [
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1548, in <listcomp>
    [
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1497, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/fields/files.py", line 316, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/fields/files.py", line 92, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/files/storage.py", line 57, in save
    name = self._save(name, content)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/files/storage.py", line 315, in _save
    fd = os.open(full_path, self.OS_OPEN_FLAGS, 0o666)
PermissionError: [Errno 13] Permission denied: '/home/yousef/Documents/Django Workspace/storefront/media/store/images/headphones-red.webp'
2022-08-22 19:26:13,777 (WARNING) - silk.model_factory - Response to request with pk 06af1455-0f40-42c7-9e02-e00b4557535a has content type text/javascript but was unable to parse it
2022-08-22 19:26:17,371 (WARNING) - silk.model_factory - Response to request with pk bd27a0f2-2a93-49a2-9438-5b306c7c286a has content type text/javascript but was unable to parse it
2022-08-22 19:26:24,807 (ERROR) - django.request - Internal Server Error: /admin/store/product/288/change/
Traceback (most recent call last):
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1888, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1745, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1798, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1248, in save_related
    self.save_formset(request, form, formset, change=change)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1236, in save_formset
    formset.save()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/forms/models.py", line 786, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/forms/models.py", line 945, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/forms/models.py", line 1141, in save_new
    return super().save_new(form, commit=commit)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/forms/models.py", line 762, in save_new
    return form.save(commit=commit)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/forms/models.py", line 548, in save
    self.instance.save()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1620, in execute_sql
    for sql, params in self.as_sql():
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1547, in as_sql
    value_rows = [
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1548, in <listcomp>
    [
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1497, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/fields/files.py", line 316, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/fields/files.py", line 92, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/files/storage.py", line 57, in save
    name = self._save(name, content)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/files/storage.py", line 315, in _save
    fd = os.open(full_path, self.OS_OPEN_FLAGS, 0o666)
PermissionError: [Errno 13] Permission denied: '/home/yousef/Documents/Django Workspace/storefront/media/store/images/headphones-blue.webp'
2022-08-22 19:31:55,005 (WARNING) - silk.model_factory - Response to request with pk 3e536e94-9b71-41b3-a2cd-852ea36f25d6 has content type text/javascript but was unable to parse it
2022-08-22 19:31:59,871 (WARNING) - silk.model_factory - Response to request with pk a1b4c6bd-4205-4b8d-ae3b-1d0ba722321f has content type text/javascript but was unable to parse it
2022-08-25 00:12:26,107 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 00:12:31,535 (WARNING) - django.request - Not Found: /favicon.ico
2022-08-25 20:12:48,394 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:12:55,735 (WARNING) - django.request - Not Found: /favicon.ico
2022-08-25 20:13:02,936 (ERROR) - django.request - Internal Server Error: /store/collections/
Traceback (most recent call last):
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/query.py", line 320, in __iter__
    self._fetch_all()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/silk/sql.py", line 65, in execute_sql
    q, params = self.as_sql()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 573, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 64, in pre_sql_setup
    self.setup_query()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 55, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 268, in get_select
    related_klass_infos = self.get_related_selections(select)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1051, in get_related_selections
    next_klass_infos = self.get_related_selections(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1158, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'product'. Choices are: collection
2022-08-25 20:13:58,035 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/views.py changed, reloading.
2022-08-25 20:13:59,346 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:14:03,259 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/views.py changed, reloading.
2022-08-25 20:14:04,557 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:14:07,555 (ERROR) - django.request - Internal Server Error: /store/collections/
Traceback (most recent call last):
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/query.py", line 320, in __iter__
    self._fetch_all()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/silk/sql.py", line 65, in execute_sql
    q, params = self.as_sql()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 573, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 64, in pre_sql_setup
    self.setup_query()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 55, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 268, in get_select
    related_klass_infos = self.get_related_selections(select)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1051, in get_related_selections
    next_klass_infos = self.get_related_selections(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1158, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'product'. Choices are: collection
2022-08-25 20:14:58,357 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/views.py changed, reloading.
2022-08-25 20:14:59,327 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:15:01,057 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/views.py changed, reloading.
2022-08-25 20:15:02,048 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:15:04,663 (ERROR) - django.request - Internal Server Error: /store/collections/
Traceback (most recent call last):
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/query.py", line 320, in __iter__
    self._fetch_all()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/silk/sql.py", line 65, in execute_sql
    q, params = self.as_sql()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 573, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 64, in pre_sql_setup
    self.setup_query()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 55, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 268, in get_select
    related_klass_infos = self.get_related_selections(select)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1158, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'product'. Choices are: featured_product
2022-08-25 20:15:13,522 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/views.py changed, reloading.
2022-08-25 20:15:14,601 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:17:53,867 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-08-25 20:17:54,945 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:18:00,847 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-08-25 20:18:01,823 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:18:08,246 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-08-25 20:18:09,197 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:18:12,487 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-08-25 20:18:13,476 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:18:16,774 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-08-25 20:18:17,631 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:18:30,066 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-08-25 20:18:31,184 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:18:47,788 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-08-25 20:18:48,787 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:19:10,853 (ERROR) - django.request - Internal Server Error: /store/collections/
Traceback (most recent call last):
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/yousef/.local/share/virtualenvs/storefront-hk1WUvhs/lib/python3.10/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'feature_product' was declared on serializer CollectionSerializer, but has not been included in the 'fields' option.
2022-08-25 20:19:43,691 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-08-25 20:19:44,594 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:22:37,305 (WARNING) - django.request - Not Found: /store/prodocts
2022-08-25 20:22:41,796 (WARNING) - django.request - Not Found: /store/producst
2022-08-25 20:39:42,731 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:40:25,380 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-08-25 20:40:26,438 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:40:35,226 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/views.py changed, reloading.
2022-08-25 20:40:36,134 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-08-25 20:40:37,829 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/views.py changed, reloading.
2022-08-25 20:40:39,445 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-06 23:03:32,559 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-06 23:03:36,851 (WARNING) - django.request - Not Found: /favicon.ico
2022-09-06 23:03:44,375 (WARNING) - django.request - Method Not Allowed: /store/carts/
2022-09-06 23:03:51,526 (ERROR) - django.request - Internal Server Error: /store/carts/
Traceback (most recent call last):
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 20, in create
    headers = self.get_success_headers(serializer.data)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/fields.py", line 1886, in to_representation
    return method(value)
  File "/home/yousef/Documents/Django Workspace/storefront/store/serializers.py", line 115, in get_total_quantity
    return sum([item.quantity for item in cart.itens.all()])
AttributeError: 'Cart' object has no attribute 'itens'
2022-09-06 23:04:22,396 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-06 23:04:23,248 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:32:42,411 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:32:47,297 (WARNING) - django.request - Not Found: /favicon.ico
2022-09-08 03:32:55,048 (WARNING) - django.request - Method Not Allowed: /store/carts/
2022-09-08 03:32:59,804 (ERROR) - django.request - Internal Server Error: /store/carts/
Traceback (most recent call last):
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 20, in create
    headers = self.get_success_headers(serializer.data)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/fields.py", line 1886, in to_representation
    return method(value)
TypeError: CartSerializer.get_total_price_with_tax() takes 1 positional argument but 2 were given
2022-09-08 03:33:21,777 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:33:22,752 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:33:25,646 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:33:26,425 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:33:40,483 (WARNING) - django.request - Not Found: /store/carts/items/
2022-09-08 03:34:01,791 (WARNING) - django.request - Bad Request: /store/carts/cd146eeb-c8b3-4446-8015-02605af070b9/items/
2022-09-08 03:34:18,983 (ERROR) - django.request - Internal Server Error: /store/carts/cd146eeb-c8b3-4446-8015-02605af070b9/
Traceback (most recent call last):
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/yousef/Documents/Django Workspace/storefront/.venv/lib/python3.10/site-packages/rest_framework/fields.py", line 1886, in to_representation
    return method(value)
  File "/home/yousef/Documents/Django Workspace/storefront/store/serializers.py", line 116, in get_total_price_with_tax
    return self.get_total_price(cart) * 1.13
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
2022-09-08 03:35:08,493 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:35:09,695 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:35:59,631 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:36:00,922 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:36:02,275 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:36:03,284 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:36:16,265 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:36:17,703 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:36:19,098 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:36:20,100 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:36:34,677 (WARNING) - django.request - Method Not Allowed: /store/carts/
2022-09-08 03:37:16,499 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:37:17,703 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:37:22,144 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:37:22,918 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:37:26,497 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:37:27,220 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:37:30,984 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:37:31,702 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:37:35,341 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:37:36,467 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:37:48,289 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:37:49,423 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:37:51,894 (INFO) - django.utils.autoreload - /home/yousef/Documents/Django Workspace/storefront/store/serializers.py changed, reloading.
2022-09-08 03:37:53,167 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2022-09-08 03:38:10,358 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
